# -*- coding: utf-8 -*-
"""sliceDiceImages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HrTXhfzfmlB3r2pElu9IKArtYIwTKXAl
"""

from google.colab import drive
drive.flush_and_unmount()
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/Colab Notebooks/

pip install image_slicer

from os import walk
import image_slicer
import os



def sliceDiceImages(path):
  print(path)
  _, _, filenames = next(walk(path))
  filenames = sorted(filenames)
  for item in filenames:
    image_slicer.slice(path+'/'+item,36)
    os.remove(path+'/'+item)

"""for this part you must define the name of your folder where you are placing both folders containing grountruths and images"""

nameOfFolder='microaneurysms new unet'


groundTruthsPath = '/content/drive/MyDrive/Colab Notebooks/'+nameOfFolder+'/groundtruths/'
imagesPath ='/content/drive/MyDrive/Colab Notebooks/'+nameOfFolder+'/images/'
imagesTestPath = imagesPath+'test'
imagesTrainingPath = imagesPath + 'training'
imagesValidationPath=imagesPath+'validation'
groundTruthsTestPath =  groundTruthsPath+'test'
groundTruthsTrainPath = groundTruthsPath+ 'training'
groundTruthsValidationPath= groundTruthsPath+'validation'

"""uncomment one and run  separately
then comment and uncomment the following
"""

print(imagesTrainingPath)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks/hard exudates new unet/images/training

sliceDiceImages(imagesTrainingPath)

sliceDiceImages(imagesTestPath)

sliceDiceImages(groundTruthsTestPath)

sliceDiceImages(groundTruthsTrainPath)

# Commented out IPython magic to ensure Python compatibility.
  diseaseFolder='hemorrages full new unet'
#   %cd /content/drive/My Drive/Colab Notebooks/
#   %cd   diseaseFolder

